package gui.backups.incremental;

import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import gui.Controller;
import gui.backups.incremental.IncrementalCreationController;
import gui.View;

/**
 *
 * @author Fedrix
 */
public class BackupCreationProgressDialog extends JDialog implements View {
    private final String title = "Creating the backup...";
    private final int DIALOG_WIDTH = 900;
    private final int DIALOG_HEIGHT = 400;
    private IncrementalCreationController controller;
    
    /**
     * Creates new form BackupCreationProgressDialog
     * @param parent
     */
    public BackupCreationProgressDialog(JFrame parent) {
        super(parent, true);
        this.setTitle(title);
        this.setResizable(false);
        this.setSize(new Dimension(DIALOG_WIDTH, DIALOG_HEIGHT));
        this.setLocation(parent.getMousePosition());
        
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                controller.cancel();
            }
        });
        initComponents();
    }

    /**
     * Set progress percentage of backup creation
     * @param progress between 0 and 100
     */
    public void setProgress(int progress){
        assert(progress >= jProgressBar.getMinimum() && progress <= jProgressBar.getMaximum());
        jTextFieldProgressPercentage.setText(Integer.toString(progress));
        jProgressBar.setValue(progress);
    }
    
    public void setWorkingFile(String file){
        jTextFieldWorkingFile.setText(file);
    }
    
    public void setWorkingTask(String task){
        jTextFieldTask.setText(task);
    }
    
    public void setTimeValue(int time){
        jLabelTimeValue.setText(time + "s");
    }
    public void appendError(String msg){
        jTextAreaErrors.append(msg);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMinimize = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jButtonClose = new javax.swing.JButton();
        jTextFieldProgressPercentage = new javax.swing.JTextField();
        jLabelProgress = new javax.swing.JLabel();
        jLabelCurrentWorkingFile = new javax.swing.JLabel();
        jLabelCurrentTask = new javax.swing.JLabel();
        jScrollPaneWorkingFile = new javax.swing.JScrollPane();
        jTextFieldWorkingFile = new javax.swing.JTextField();
        jTextFieldTask = new javax.swing.JTextField();
        jLabelTime = new javax.swing.JLabel();
        jLabelTimeValue = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPaneErrors = new javax.swing.JScrollPane();
        jTextAreaErrors = new javax.swing.JTextArea();
        jLabelErrors = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonMinimize.setText("Minimize");
        jButtonMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizeActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jTextFieldProgressPercentage.setEditable(false);
        jTextFieldProgressPercentage.setText("0%");
        jTextFieldProgressPercentage.setFocusable(false);

        jLabelProgress.setText("Progress:");

        jLabelCurrentWorkingFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCurrentWorkingFile.setText("Current working file");

        jLabelCurrentTask.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCurrentTask.setText("Current task");

        jTextFieldWorkingFile.setEditable(false);
        jTextFieldWorkingFile.setFocusable(false);
        jScrollPaneWorkingFile.setViewportView(jTextFieldWorkingFile);

        jTextFieldTask.setEditable(false);
        jTextFieldTask.setFocusable(false);

        jLabelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTime.setText("Time:");

        jLabelTimeValue.setText("0s");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextAreaErrors.setEditable(false);
        jTextAreaErrors.setColumns(20);
        jTextAreaErrors.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jTextAreaErrors.setRows(5);
        jTextAreaErrors.setFocusable(false);
        jScrollPaneErrors.setViewportView(jTextAreaErrors);

        jLabelErrors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelErrors.setText("Errors");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCurrentTask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldTask)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(287, 287, 287)
                                    .addComponent(jButtonMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldProgressPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(266, 266, 266)
                                    .addComponent(jLabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelTimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelCurrentWorkingFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPaneWorkingFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneErrors, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(jLabelErrors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldProgressPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTimeValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(jLabelCurrentWorkingFile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneWorkingFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabelCurrentTask, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTask, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelErrors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPaneErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizeActionPerformed
        if(this.getParent() instanceof JFrame f){
            f.setState(JFrame.ICONIFIED);
        }
    }//GEN-LAST:event_jButtonMinimizeActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        controller.cancel();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    @Override
    public <T extends Controller> void setController(T controller) {
        this.controller = controller.toIncrementalCreationController();
    }

    @Override
    public BackupCreationProgressDialog toBackupCreationProgressDialog() {
        return this;
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonMinimize;
    private javax.swing.JLabel jLabelCurrentTask;
    private javax.swing.JLabel jLabelCurrentWorkingFile;
    private javax.swing.JLabel jLabelErrors;
    private javax.swing.JLabel jLabelProgress;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTimeValue;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPaneErrors;
    private javax.swing.JScrollPane jScrollPaneWorkingFile;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaErrors;
    private javax.swing.JTextField jTextFieldProgressPercentage;
    private javax.swing.JTextField jTextFieldTask;
    private javax.swing.JTextField jTextFieldWorkingFile;
    // End of variables declaration//GEN-END:variables
}
