package gui.strategy.creation;
import gui.strategy.StrategyDialog;
import gui.Controller;
import javax.swing.BoundedRangeModel;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import javax.swing.ListModel;

/**
 *
 * @author Fedrix
 */
public class StrategyCreationDialog extends StrategyDialog {
    private final String title = "Create Strategies";
    private StrategyCreationController controller;
    
    public StrategyCreationDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        this.setTitle(title);
        this.setResizable(false);
        initComponents();
    }
    
    
    public void setStrategyName(String name){
        jTextFieldStrategyName.setText(name);
    }
    
    public void setDestFolder(String dest){
        jTextFieldDestFolder.setText(dest);
    }
    
    public void setTargetsList(ListModel<String> model){
        jListTargets.setModel(model);
    }
    
    public void setEncryptionComboBoxModel(ComboBoxModel model){
        jCBEncryption.setModel(model);
    }
    public void setCompressionComboBoxModel(ComboBoxModel model){
        jCBCompression.setModel(model);
    }
    public void setMaxIncrementsLimitSliderModel(BoundedRangeModel model){
        jSliderMaxIncrements.setModel(model);
        jSliderMaxIncrements.setMaximum(model.getMaximum());
        jSliderMaxIncrements.setMinimum(model.getMinimum());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStrategyName = new javax.swing.JLabel();
        jLabelCompression = new javax.swing.JLabel();
        jLabelEncryption = new javax.swing.JLabel();
        jLabelDestFolder = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonDestFolder = new javax.swing.JButton();
        jTextFieldStrategyName = new javax.swing.JTextField();
        jCBEncryption = new javax.swing.JComboBox<>();
        jCBCompression = new javax.swing.JComboBox<>();
        jButtonAddTarget = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTargets = new javax.swing.JList<>();
        jButtonCreateStrategy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFieldDestFolder = new javax.swing.JTextField();
        jButtonDeleteSelectedTarget = new javax.swing.JButton();
        jButtonManageFilters = new javax.swing.JButton();
        jLabelMaxIncrements = new javax.swing.JLabel();
        jSliderMaxIncrements = new javax.swing.JSlider();
        jButtonHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelStrategyName.setText("Strategy Name");

        jLabelCompression.setText("Compression");

        jLabelEncryption.setText("Encryption");

        jLabelDestFolder.setText("Destination Folder");

        jButtonDestFolder.setText("Set Folder");
        jButtonDestFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDestFolderActionPerformed(evt);
            }
        });

        jTextFieldStrategyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStrategyNameActionPerformed(evt);
            }
        });

        jButtonAddTarget.setText("Add item to backup");
        jButtonAddTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTargetActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListTargets);

        jButtonCreateStrategy.setText("Create");
        jButtonCreateStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateStrategyActionPerformed(evt);
            }
        });

        jTextFieldDestFolder.setEditable(false);
        jTextFieldDestFolder.setFocusable(false);
        jScrollPane2.setViewportView(jTextFieldDestFolder);

        jButtonDeleteSelectedTarget.setText("Delete selected");
        jButtonDeleteSelectedTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSelectedTargetActionPerformed(evt);
            }
        });

        jButtonManageFilters.setText("Manage Filters");
        jButtonManageFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageFiltersActionPerformed(evt);
            }
        });

        jLabelMaxIncrements.setText("Max Increments");

        jSliderMaxIncrements.setMajorTickSpacing(1);
        jSliderMaxIncrements.setMaximum(10);
        jSliderMaxIncrements.setPaintLabels(true);
        jSliderMaxIncrements.setPaintTicks(true);

        jButtonHelp.setText("Help");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButtonAddTarget)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteSelectedTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelMaxIncrements, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSliderMaxIncrements, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCompression, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(jLabelEncryption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBCompression, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBEncryption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDestFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelStrategyName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldStrategyName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDestFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jButtonManageFilters, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(595, Short.MAX_VALUE)
                    .addComponent(jButtonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonCreateStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStrategyName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStrategyName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBEncryption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEncryption, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCompression, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBCompression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDestFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonDestFolder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMaxIncrements, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderMaxIncrements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jButtonManageFilters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeleteSelectedTarget)
                    .addComponent(jButtonAddTarget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(550, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCreateStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDestFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDestFolderActionPerformed
        controller.pickDestinationFolder();
    }//GEN-LAST:event_jButtonDestFolderActionPerformed

    private void jButtonAddTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTargetActionPerformed
        controller.addTarget();
    }//GEN-LAST:event_jButtonAddTargetActionPerformed

    private void jButtonCreateStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateStrategyActionPerformed
        controller.createStrategy(jTextFieldStrategyName.getText(), jTextFieldDestFolder.getText());
    }//GEN-LAST:event_jButtonCreateStrategyActionPerformed

    private void jButtonDeleteSelectedTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSelectedTargetActionPerformed
        if(jListTargets.getSelectedValue() != null){
            controller.removeTarget(jListTargets.getSelectedValue());
        }
    }//GEN-LAST:event_jButtonDeleteSelectedTargetActionPerformed

    private void jButtonManageFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageFiltersActionPerformed
        controller.manageFilters();
    }//GEN-LAST:event_jButtonManageFiltersActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        super.displayHelp();
    }//GEN-LAST:event_jButtonHelpActionPerformed

    private void jTextFieldStrategyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStrategyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStrategyNameActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTarget;
    private javax.swing.JButton jButtonCreateStrategy;
    private javax.swing.JButton jButtonDeleteSelectedTarget;
    private javax.swing.JButton jButtonDestFolder;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonManageFilters;
    private javax.swing.JComboBox<String> jCBCompression;
    private javax.swing.JComboBox<String> jCBEncryption;
    private javax.swing.JLabel jLabelCompression;
    private javax.swing.JLabel jLabelDestFolder;
    private javax.swing.JLabel jLabelEncryption;
    private javax.swing.JLabel jLabelMaxIncrements;
    private javax.swing.JLabel jLabelStrategyName;
    private javax.swing.JList<String> jListTargets;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSliderMaxIncrements;
    private javax.swing.JTextField jTextFieldDestFolder;
    private javax.swing.JTextField jTextFieldStrategyName;
    // End of variables declaration//GEN-END:variables

    @Override
    public <ctrlT extends Controller> void setController(ctrlT c) {
        controller = c.toStrategyCreationController();
    }

    @Override
    public StrategyCreationDialog toStrategyCreationDialog() {
        return this;
    }

    
}
