package gui.journal.rollback;

import gui.CenteredDialog;
import gui.Controller;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.ListModel;


public class JournalRollbackDialog extends CenteredDialog {
    protected final int DIALOG_WIDTH = 600;
    protected final int DIALOG_HEIGHT = 600;
    private static final String title = "Manage journals and rollback";
    private JournalRollbackController controller;
    
    /**
     * Creates new form JournalRollbackDialog
     * @param parent
     * @param modal
     */
    public JournalRollbackDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        this.setTitle(title);
        this.setMinimumSize(new Dimension(DIALOG_WIDTH, DIALOG_HEIGHT));
        this.setResizable(false);
        initComponents();
    }

    public void setJournalsListModel(ListModel<String> model){
        jListJournals.setModel(model);
    }
    
    /**
     * 
     * @return the index of the selected item, -1 is there is no selection
     */
    public int getSelectedIndex(){
        return jListJournals.getSelectedIndex();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListJournals = new javax.swing.JList<>();
        jSeparator = new javax.swing.JSeparator();
        JButtonSeeJournalData = new javax.swing.JButton();
        JButtonRollback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("A journal is a log file containing all informations about a made backup.\nBackups use these file to know which changes has been made.\n\nJournal rollback is used to delete journals so that the next backup will contain \nall data since the time the rollback was made (included). \n\nSelect an item to continue.");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jListJournals.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListJournals);

        JButtonSeeJournalData.setText("See Journal Data");
        JButtonSeeJournalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSeeJournalDataActionPerformed(evt);
            }
        });

        JButtonRollback.setText("Rollback");
        JButtonRollback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRollbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JButtonSeeJournalData, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonRollback, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JButtonSeeJournalData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonRollback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonSeeJournalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSeeJournalDataActionPerformed
        controller.seeJournalData();
    }//GEN-LAST:event_JButtonSeeJournalDataActionPerformed

    private void JButtonRollbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRollbackActionPerformed
        controller.rollback();
    }//GEN-LAST:event_JButtonRollbackActionPerformed

    @Override
    public <T extends Controller> void setController(T controller) {
        this.controller = controller.toJournalRollbackController();
    }

    @Override
    public JournalRollbackDialog toJournalRollbackDialog() {
        return this;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonRollback;
    private javax.swing.JButton JButtonSeeJournalData;
    private javax.swing.JList<String> jListJournals;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
