package gui.journal;

import core.journal.Journal;
import java.awt.Dimension;
import javax.swing.table.TableModel;
import gui.Controller;
import gui.CenteredDialog;
import javax.swing.JDialog;
import javax.swing.JFrame;
import utils.formatters.EasyDateTimeFormatter;

/**
 * A static dialog showing information of a journal
 * @author Fedrix
 */
public class JournalDataDialog extends CenteredDialog {
    private final int DIALOG_WIDTH = 900;
    private final int DIALOG_HEIGHT = 500;
    private final String title = "Journal of strategy: %s [Type: %s] - Created on %s";
    
    
    /**
     * Creates new form which can be used to display all data of a journal
     * @param parent
     * @param modal
     * @param journal
     */
    public JournalDataDialog(JDialog parent, boolean modal, Journal journal) {
        super(parent, modal);
        this.setTitle(title.formatted(journal.strategyID, journal.type, EasyDateTimeFormatter.getFormatted(journal.getCreatedTime())));
        this.setMinimumSize(new Dimension(DIALOG_WIDTH, DIALOG_HEIGHT));
        initComponents();
    }
    
    /**
     * Creates new form which can be used to display all data of a journal
     * @param parent
     * @param modal
     * @param journal
     */
    public JournalDataDialog(JFrame parent, boolean modal, Journal journal) {
        super(parent, modal);
        this.setTitle(title.formatted(journal.strategyID, journal.type, EasyDateTimeFormatter.getFormatted(journal.getCreatedTime())));
        this.setMinimumSize(new Dimension(DIALOG_WIDTH, DIALOG_HEIGHT));
        initComponents();
    }
    

    public void setTableModel(TableModel model){
        jTableFiles.setModel(model);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTableFiles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jTableFiles.setAutoCreateRowSorter(true);
        jTableFiles.setEnabled(false);
        jTableFiles.setFocusable(false);
        jScrollPane.setViewportView(jTableFiles);

        getContentPane().add(jScrollPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    @Override
    public <T extends Controller> void setController(T controller) {}

    @Override
    public JournalDataDialog toJournalDataDialog() {
        return this;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableFiles;
    // End of variables declaration//GEN-END:variables
}
