package gui.mainwindow.view.main;
import gui.Controller;
import gui.mainwindow.MainWindowController;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;
import javax.swing.tree.TreeModel;
import settings.Theme;
import gui.View;

/**
 * The main JFrame window of the program
 * @author Fedrix
 */
public class MainWindow extends javax.swing.JFrame implements View{
    private final Dimension controlsSize = new Dimension(250, 40);
    private final Dimension minimumSize = MainWindowSizes.getMinSize();
    private MainWindowController controller;
    private Theme theme;
    private Color dataPanelColor;
    private Color textStatusColor;
    
    
    /**
     * Constructor
     * @param title window title
     * @param width window width in pixel
     * @param height window height in pixel
     * @param theme theme of the main window
     */
    public MainWindow(String title, int width, int height, Theme theme) {
        super(title);
        this.setMinimumSize(minimumSize);
        this.setPreferredSize(new Dimension(width, height));
        this.setLocationRelativeTo(null);
        this.setResizable(true);
        // Setting up theme
        this.theme = theme;
        applyTheme();
        // Inizialing components
        initComponents();
    }
    
    
    /**
     * This method is used to change every appearance component that depends of the chosen theme
     */
    private void applyTheme(){
        switch(theme){
            case Dark -> {
                textStatusColor = Color.WHITE;
            }
            case Light -> {
                textStatusColor = Color.BLACK;
            }
        }
    }
    
    /**
     * Push a new line to the window status
     * @param line 
     */
    public void pushStatus(String line){
        jTextAreaStatus.append(line + System.lineSeparator());
    }
    
    /**
     * Set the tip label
     * @param line 
     */
    public void setTip(String line){
        jLabelTip.setText(line);
    }
    
    public void setStrategiesListModel(ListModel<String> model){
        jListStrategies.setModel(model);
    }
    
    public void setTargetsListModel(ListModel<String> model, ListCellRenderer renderer){
        jListTargets.setModel(model);
        jListTargets.setCellRenderer(renderer);
    }
    
    public void setDestTreeModel(TreeModel model){
        jTreeDest.setModel(model);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelCenter = new javax.swing.JPanel();
        jPanelData = new javax.swing.JPanel();
        jPaneDataSrc = new javax.swing.JPanel();
        jLabelSrc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTargets = new javax.swing.JList<>();
        jPanelDataDst = new javax.swing.JPanel();
        jLabelDst = new javax.swing.JLabel();
        jScrollPaneDst = new javax.swing.JScrollPane();
        jTreeDest = new javax.swing.JTree();
        jPanelNorth = new javax.swing.JPanel();
        jLabelTip = new javax.swing.JLabel();
        jSeparatorNorth = new javax.swing.JSeparator();
        jPanelSouth = new javax.swing.JPanel();
        jScrollPaneStatus = new javax.swing.JScrollPane();
        jTextAreaStatus = new javax.swing.JTextArea();
        jPanelStatusBottom = new javax.swing.JPanel();
        jLabelVersionInfo = new javax.swing.JLabel();
        jPaneEast = new javax.swing.JPanel();
        jLabelAvailableStrat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListStrategies = new javax.swing.JList<>();
        jButtonLoadStrategy = new javax.swing.JButton();
        jPanelWest = new javax.swing.JPanel();
        jPanelBackupCtrl = new javax.swing.JPanel();
        jLabelBkpCtrlTitle = new javax.swing.JLabel();
        jButtonNewBkp = new javax.swing.JButton();
        jButtonAutoIntegrityVerification = new javax.swing.JButton();
        jButtonManualIntegrityVerification = new javax.swing.JButton();
        jButtonManageJournals = new javax.swing.JButton();
        jPanelStratCtrl = new javax.swing.JPanel();
        jLabelStratCtrlTitle = new javax.swing.JLabel();
        jButtonNewStrategies = new javax.swing.JButton();
        jButtonManageStrategies = new javax.swing.JButton();
        jMenuBarTop = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemNewBkp = new javax.swing.JMenuItem();
        jMenuItemAutoIntegrity = new javax.swing.JMenuItem();
        jMenuItemManualIntegrity = new javax.swing.JMenuItem();
        jMenuItemManageJournals = new javax.swing.JMenuItem();
        jSeparatorFileMenu1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemNewStrat = new javax.swing.JMenuItem();
        jMenuItemManageStrategies = new javax.swing.JMenuItem();
        jSeparatorFileMenu2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuPreferencies = new javax.swing.JMenu();
        jMenuItemSettings = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItemSourceCode = new javax.swing.JMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setLayout(new java.awt.BorderLayout());

        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jPanelData.setLayout(new javax.swing.BoxLayout(jPanelData, javax.swing.BoxLayout.Y_AXIS));

        jPaneDataSrc.setBackground(dataPanelColor);
        jPaneDataSrc.setLayout(new javax.swing.BoxLayout(jPaneDataSrc, javax.swing.BoxLayout.Y_AXIS));

        jLabelSrc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelSrc.setText("Source");
        jLabelSrc.setAlignmentX(Component.CENTER_ALIGNMENT);
        jLabelSrc.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabelSrc.setMinimumSize(new java.awt.Dimension(56, 20));
        jLabelSrc.setName(""); // NOI18N
        jLabelSrc.setPreferredSize(new java.awt.Dimension(56, 20));
        jPaneDataSrc.add(jLabelSrc);

        jScrollPane2.setViewportView(jListTargets);

        jPaneDataSrc.add(jScrollPane2);

        jPanelData.add(jPaneDataSrc);

        jPanelDataDst.setBackground(dataPanelColor);
        jPanelDataDst.setName(""); // NOI18N
        jPanelDataDst.setPreferredSize(new java.awt.Dimension(178, 200));
        jPanelDataDst.setLayout(new javax.swing.BoxLayout(jPanelDataDst, javax.swing.BoxLayout.Y_AXIS));

        jLabelDst.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelDst.setText("Destination");
        jLabelDst.setAlignmentX(Component.CENTER_ALIGNMENT);
        jLabelDst.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabelDst.setMinimumSize(new java.awt.Dimension(89, 20));
        jLabelDst.setPreferredSize(new java.awt.Dimension(89, 20));
        jPanelDataDst.add(jLabelDst);

        jTreeDest.setModel(null);
        jScrollPaneDst.setViewportView(jTreeDest);

        jPanelDataDst.add(jScrollPaneDst);

        jPanelData.add(jPanelDataDst);

        jPanelCenter.add(jPanelData, java.awt.BorderLayout.CENTER);

        jPanelMain.add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 2, 0));
        jPanelNorth.setLayout(new javax.swing.BoxLayout(jPanelNorth, javax.swing.BoxLayout.Y_AXIS));

        jLabelTip.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        jLabelTip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTip.setText("Load a strategy or create a new one to start");
        jLabelTip.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelTip.setAlignmentX(Component.CENTER_ALIGNMENT);
        jPanelNorth.add(jLabelTip);
        jPanelNorth.add(jSeparatorNorth);

        jPanelMain.add(jPanelNorth, java.awt.BorderLayout.PAGE_START);

        jPanelSouth.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        jPanelSouth.setLayout(new javax.swing.BoxLayout(jPanelSouth, javax.swing.BoxLayout.Y_AXIS));

        jTextAreaStatus.setEditable(false);
        jTextAreaStatus.setColumns(20);
        jTextAreaStatus.setRows(8);
        jTextAreaStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextAreaStatus.setDisabledTextColor(textStatusColor);
        jTextAreaStatus.setEnabled(false);
        jTextAreaStatus.setHighlighter(null);
        jScrollPaneStatus.setViewportView(jTextAreaStatus);

        jPanelSouth.add(jScrollPaneStatus);

        jPanelStatusBottom.setLayout(new java.awt.BorderLayout());

        jLabelVersionInfo.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabelVersionInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVersionInfo.setText("Version 1.0");
        jLabelVersionInfo.setPreferredSize(new java.awt.Dimension(60, 16));
        jPanelStatusBottom.add(jLabelVersionInfo, java.awt.BorderLayout.CENTER);

        jPanelSouth.add(jPanelStatusBottom);

        jPanelMain.add(jPanelSouth, java.awt.BorderLayout.PAGE_END);

        jPaneEast.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jPaneEast.setPreferredSize(new java.awt.Dimension(250, 355));
        jPaneEast.setLayout(new javax.swing.BoxLayout(jPaneEast, javax.swing.BoxLayout.Y_AXIS));

        jLabelAvailableStrat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelAvailableStrat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAvailableStrat.setText("Available Strategies");
        jLabelAvailableStrat.setAlignmentX(Component.CENTER_ALIGNMENT);
        jLabelAvailableStrat.setMaximumSize(new java.awt.Dimension(174, 20));
        jLabelAvailableStrat.setMinimumSize(new java.awt.Dimension(174, 20));
        jLabelAvailableStrat.setPreferredSize(new java.awt.Dimension(174, 20));
        jPaneEast.add(jLabelAvailableStrat);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(258, 126));

        jScrollPane1.setViewportView(jListStrategies);

        jPaneEast.add(jScrollPane1);

        jButtonLoadStrategy.setText("Load Strategy");
        jButtonLoadStrategy.setAlignmentX(Component.CENTER_ALIGNMENT);
        jButtonLoadStrategy.setMaximumSize(new java.awt.Dimension(258, 26));
        jButtonLoadStrategy.setMinimumSize(new java.awt.Dimension(140, 26));
        jButtonLoadStrategy.setPreferredSize(new java.awt.Dimension(258, 26));
        jButtonLoadStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadStrategyActionPerformed(evt);
            }
        });
        jPaneEast.add(jButtonLoadStrategy);

        jPanelMain.add(jPaneEast, java.awt.BorderLayout.LINE_END);

        jPanelWest.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        jPanelWest.setLayout(new javax.swing.BoxLayout(jPanelWest, javax.swing.BoxLayout.Y_AXIS));

        jPanelBackupCtrl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        jPanelBackupCtrl.setLayout(new javax.swing.BoxLayout(jPanelBackupCtrl, javax.swing.BoxLayout.Y_AXIS));

        jLabelBkpCtrlTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelBkpCtrlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBkpCtrlTitle.setText("Backups Controls");
        jLabelBkpCtrlTitle.setMaximumSize(controlsSize);
        jPanelBackupCtrl.add(jLabelBkpCtrlTitle);

        jButtonNewBkp.setFont(new java.awt.Font("Garuda", 0, 16)); // NOI18N
        jButtonNewBkp.setText("New Backup");
        jButtonNewBkp.setMaximumSize(controlsSize);
        jButtonNewBkp.setPreferredSize(controlsSize);
        jButtonNewBkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewBkpActionPerformed(evt);
            }
        });
        jPanelBackupCtrl.add(jButtonNewBkp);

        jButtonAutoIntegrityVerification.setFont(new java.awt.Font("Garuda", 0, 16)); // NOI18N
        jButtonAutoIntegrityVerification.setText("Auto Integrity Verification");
        jButtonAutoIntegrityVerification.setMaximumSize(controlsSize);
        jButtonAutoIntegrityVerification.setPreferredSize(controlsSize);
        jButtonAutoIntegrityVerification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoIntegrityVerificationActionPerformed(evt);
            }
        });
        jPanelBackupCtrl.add(jButtonAutoIntegrityVerification);

        jButtonManualIntegrityVerification.setFont(new java.awt.Font("Garuda", 0, 16)); // NOI18N
        jButtonManualIntegrityVerification.setText("Manual Integrity Verification");
        jButtonManualIntegrityVerification.setMaximumSize(controlsSize);
        jButtonManualIntegrityVerification.setPreferredSize(controlsSize);
        jButtonManualIntegrityVerification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManualIntegrityVerificationActionPerformed(evt);
            }
        });
        jPanelBackupCtrl.add(jButtonManualIntegrityVerification);

        jButtonManageJournals.setFont(new java.awt.Font("Garuda", 0, 16)); // NOI18N
        jButtonManageJournals.setText("Manage Journals");
        jButtonManageJournals.setMaximumSize(controlsSize);
        jButtonManageJournals.setPreferredSize(controlsSize);
        jButtonManageJournals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageJournalsActionPerformed(evt);
            }
        });
        jPanelBackupCtrl.add(jButtonManageJournals);

        jPanelWest.add(jPanelBackupCtrl);

        jPanelStratCtrl.setLayout(new javax.swing.BoxLayout(jPanelStratCtrl, javax.swing.BoxLayout.Y_AXIS));

        jLabelStratCtrlTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelStratCtrlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStratCtrlTitle.setText("Strategies Controls");
        jLabelStratCtrlTitle.setMaximumSize(controlsSize);
        jPanelStratCtrl.add(jLabelStratCtrlTitle);

        jButtonNewStrategies.setFont(new java.awt.Font("Garuda", 0, 16)); // NOI18N
        jButtonNewStrategies.setText("New Strategy");
        jButtonNewStrategies.setMaximumSize(controlsSize);
        jButtonNewStrategies.setPreferredSize(controlsSize);
        jButtonNewStrategies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewStrategiesActionPerformed(evt);
            }
        });
        jPanelStratCtrl.add(jButtonNewStrategies);

        jButtonManageStrategies.setFont(new java.awt.Font("Garuda", 0, 16)); // NOI18N
        jButtonManageStrategies.setText("Manage Strategies");
        jButtonManageStrategies.setMaximumSize(controlsSize);
        jButtonManageStrategies.setPreferredSize(controlsSize);
        jButtonManageStrategies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageStrategiesActionPerformed(evt);
            }
        });
        jPanelStratCtrl.add(jButtonManageStrategies);

        jPanelWest.add(jPanelStratCtrl);

        jPanelMain.add(jPanelWest, java.awt.BorderLayout.LINE_START);

        jMenuFile.setText("File");

        jMenuItemNewBkp.setText("New Backup");
        jMenuItemNewBkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewBkpActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemNewBkp);

        jMenuItemAutoIntegrity.setText("Auto Integrity Verification");
        jMenuItemAutoIntegrity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutoIntegrityActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemAutoIntegrity);

        jMenuItemManualIntegrity.setText("Manual Integrity Verification");
        jMenuItemManualIntegrity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManualIntegrityActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemManualIntegrity);

        jMenuItemManageJournals.setText("Manage Journals");
        jMenuItemManageJournals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageJournalsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemManageJournals);
        jMenuFile.add(jSeparatorFileMenu1);

        jMenuItemNewStrat.setText("New Strategy");
        jMenuItemNewStrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewStratActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemNewStrat);

        jMenuItemManageStrategies.setText("Manage Strategies");
        jMenuItemManageStrategies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageStrategiesActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemManageStrategies);
        jMenuFile.add(jSeparatorFileMenu2);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBarTop.add(jMenuFile);

        jMenuPreferencies.setText("Preferencies");

        jMenuItemSettings.setText("Settings");
        jMenuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSettingsActionPerformed(evt);
            }
        });
        jMenuPreferencies.add(jMenuItemSettings);

        jMenuBarTop.add(jMenuPreferencies);

        jMenuAbout.setText("About");

        jMenuItemSourceCode.setText("Source Code");
        jMenuItemSourceCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSourceCodeActionPerformed(evt);
            }
        });
        jMenuAbout.add(jMenuItemSourceCode);

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuAbout.add(jMenuItemAbout);

        jMenuBarTop.add(jMenuAbout);

        setJMenuBar(jMenuBarTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonNewBkpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewBkpActionPerformed
        controller.newBackup();
    }//GEN-LAST:event_jButtonNewBkpActionPerformed

    private void jButtonAutoIntegrityVerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoIntegrityVerificationActionPerformed
        controller.checkBackupIntegrity(true);
    }//GEN-LAST:event_jButtonAutoIntegrityVerificationActionPerformed

    private void jButtonManageStrategiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageStrategiesActionPerformed
        controller.manageStrategies();
    }//GEN-LAST:event_jButtonManageStrategiesActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        controller.exit();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemNewBkpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewBkpActionPerformed
        controller.newBackup();
    }//GEN-LAST:event_jMenuItemNewBkpActionPerformed

    private void jMenuItemNewStratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewStratActionPerformed
        controller.newStrategy();
    }//GEN-LAST:event_jMenuItemNewStratActionPerformed

    private void jMenuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSettingsActionPerformed
        controller.settings();
    }//GEN-LAST:event_jMenuItemSettingsActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        controller.about();
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemAutoIntegrityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutoIntegrityActionPerformed
        controller.checkBackupIntegrity(true);
    }//GEN-LAST:event_jMenuItemAutoIntegrityActionPerformed

    private void jButtonNewStrategiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewStrategiesActionPerformed
        controller.newStrategy();
    }//GEN-LAST:event_jButtonNewStrategiesActionPerformed

    private void jButtonLoadStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadStrategyActionPerformed
        int selected = jListStrategies.getSelectedIndex();
        if(selected != -1){
            controller.loadStrategy(selected);
        } else {
            JOptionPane.showMessageDialog(this, "Select a strategy first!");
        }
    }//GEN-LAST:event_jButtonLoadStrategyActionPerformed

    private void jMenuItemManualIntegrityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManualIntegrityActionPerformed
        controller.checkBackupIntegrity(false);
    }//GEN-LAST:event_jMenuItemManualIntegrityActionPerformed

    private void jButtonManualIntegrityVerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualIntegrityVerificationActionPerformed
        controller.checkBackupIntegrity(false);
    }//GEN-LAST:event_jButtonManualIntegrityVerificationActionPerformed

    private void jButtonManageJournalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageJournalsActionPerformed
        controller.rollbackJournal();
    }//GEN-LAST:event_jButtonManageJournalsActionPerformed

    private void jMenuItemManageJournalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageJournalsActionPerformed
        controller.rollbackJournal();
    }//GEN-LAST:event_jMenuItemManageJournalsActionPerformed

    private void jMenuItemManageStrategiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageStrategiesActionPerformed
        controller.manageStrategies();
    }//GEN-LAST:event_jMenuItemManageStrategiesActionPerformed

    private void jMenuItemSourceCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSourceCodeActionPerformed
        JOptionPane.showMessageDialog(this, "Not supported yet.");
    }//GEN-LAST:event_jMenuItemSourceCodeActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAutoIntegrityVerification;
    private javax.swing.JButton jButtonLoadStrategy;
    private javax.swing.JButton jButtonManageJournals;
    private javax.swing.JButton jButtonManageStrategies;
    private javax.swing.JButton jButtonManualIntegrityVerification;
    private javax.swing.JButton jButtonNewBkp;
    private javax.swing.JButton jButtonNewStrategies;
    private javax.swing.JLabel jLabelAvailableStrat;
    private javax.swing.JLabel jLabelBkpCtrlTitle;
    private javax.swing.JLabel jLabelDst;
    private javax.swing.JLabel jLabelSrc;
    private javax.swing.JLabel jLabelStratCtrlTitle;
    private javax.swing.JLabel jLabelTip;
    private javax.swing.JLabel jLabelVersionInfo;
    private javax.swing.JList<String> jListStrategies;
    private javax.swing.JList<String> jListTargets;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBarTop;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemAutoIntegrity;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemManageJournals;
    private javax.swing.JMenuItem jMenuItemManageStrategies;
    private javax.swing.JMenuItem jMenuItemManualIntegrity;
    private javax.swing.JMenuItem jMenuItemNewBkp;
    private javax.swing.JMenuItem jMenuItemNewStrat;
    private javax.swing.JMenuItem jMenuItemSettings;
    private javax.swing.JMenuItem jMenuItemSourceCode;
    private javax.swing.JMenu jMenuPreferencies;
    private javax.swing.JPanel jPaneDataSrc;
    private javax.swing.JPanel jPaneEast;
    private javax.swing.JPanel jPanelBackupCtrl;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JPanel jPanelDataDst;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JPanel jPanelStatusBottom;
    private javax.swing.JPanel jPanelStratCtrl;
    private javax.swing.JPanel jPanelWest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneDst;
    private javax.swing.JScrollPane jScrollPaneStatus;
    private javax.swing.JPopupMenu.Separator jSeparatorFileMenu1;
    private javax.swing.JPopupMenu.Separator jSeparatorFileMenu2;
    private javax.swing.JSeparator jSeparatorNorth;
    private javax.swing.JTextArea jTextAreaStatus;
    private javax.swing.JTree jTreeDest;
    // End of variables declaration//GEN-END:variables

    @Override
    public <ctrlT extends Controller> void setController(ctrlT c) {
        controller = (MainWindowController) c;
    }

    @Override
    public MainWindow toMainWindow() {
        return this;
    }

    

}
