package gui.strategy.management;

import gui.Controller;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import javax.swing.ListModel;
import gui.strategy.StrategyDialog;
import javax.swing.BoundedRangeModel;

/**
 * Dialog to edit and delete strategies
 * @author Fedrix
 */
public class StrategyManagementDialog extends StrategyDialog<StrategyManagementModel> {
    private final String title = "Edit and Delete Strategies";
    private StrategyManagementController controller;
    
    /**
     * StrategyManager.size() must be > 0 (Makes no sense to create a dialog to manage 0 strategies)
     * @param parent
     * @param modal 
     */
    public StrategyManagementDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        this.setTitle(title);
        this.setResizable(false);
        initComponents();
    }
    

    @Override
    public void setDestFolder(String dest){
        jTextFieldDestFolder.setText(dest);
    }
    
    public void setStrategyID(long id){
        jLabelIDValue.setText(Long.toString(id));
    }
    
    public void setStrategyNameValue(String name){
        jTextFieldStrategyNameValue.setText(name);
    }
    
    public void setTargetsList(ListModel<String> model){
        jListTargets.setModel(model);
    }
    
    public void setEncryptionComboBoxModel(ComboBoxModel model){
        jCBEncryption.setModel(model);
    }
    public void setCompressionComboBoxModel(ComboBoxModel model){
        jCBCompression.setModel(model);
    }
    public void setStrategyComboBoxModel(ComboBoxModel model){
        jCBStrategiesList.setModel(model);
    }
    public void setMaxIncrementsLimitSliderModel(BoundedRangeModel model){
        jSliderMaxIncrements.setModel(model);
        jSliderMaxIncrements.setMaximum(model.getMaximum());
        jSliderMaxIncrements.setMinimum(model.getMinimum());
    }
    
    public String getStrategyNameValue(){
        return jTextFieldStrategyNameValue.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelID = new javax.swing.JLabel();
        jLabelCompression = new javax.swing.JLabel();
        jLabelEncryption = new javax.swing.JLabel();
        jLabelDestFolder = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonChangeDestFolder = new javax.swing.JButton();
        jCBEncryption = new javax.swing.JComboBox<>();
        jCBCompression = new javax.swing.JComboBox<>();
        jButtonAddTarget = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTargets = new javax.swing.JList<>();
        jScrollPaneDestFolder = new javax.swing.JScrollPane();
        jTextFieldDestFolder = new javax.swing.JTextField();
        jButtonEditStrategy = new javax.swing.JButton();
        jCBStrategiesList = new javax.swing.JComboBox<>();
        jButtonDeleteStrategy = new javax.swing.JButton();
        jButtonDeleteSelectedStrategy = new javax.swing.JButton();
        jButtonManageFilters = new javax.swing.JButton();
        jLabelMaxIncrements = new javax.swing.JLabel();
        jSliderMaxIncrements = new javax.swing.JSlider();
        jButtonHelp = new javax.swing.JButton();
        jLabelStrategyName1 = new javax.swing.JLabel();
        jLabelIDValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldStrategyNameValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelID.setText("ID");

        jLabelCompression.setText("Compression");

        jLabelEncryption.setText("Encryption");

        jLabelDestFolder.setText("Destination Folder");

        jButtonChangeDestFolder.setText("Change Folder");
        jButtonChangeDestFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeDestFolderActionPerformed(evt);
            }
        });

        jButtonAddTarget.setText("Add item to backup");
        jButtonAddTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTargetActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListTargets);

        jTextFieldDestFolder.setEditable(false);
        jTextFieldDestFolder.setFocusable(false);
        jScrollPaneDestFolder.setViewportView(jTextFieldDestFolder);

        jButtonEditStrategy.setText("Edit");
        jButtonEditStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditStrategyActionPerformed(evt);
            }
        });

        jCBStrategiesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBStrategiesListActionPerformed(evt);
            }
        });

        jButtonDeleteStrategy.setText("Delete");
        jButtonDeleteStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteStrategyActionPerformed(evt);
            }
        });

        jButtonDeleteSelectedStrategy.setText("Delete selected");
        jButtonDeleteSelectedStrategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSelectedStrategyActionPerformed(evt);
            }
        });

        jButtonManageFilters.setText("Manage Filters");
        jButtonManageFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageFiltersActionPerformed(evt);
            }
        });

        jLabelMaxIncrements.setText("Max Increments");

        jSliderMaxIncrements.setMajorTickSpacing(1);
        jSliderMaxIncrements.setMaximum(10);
        jSliderMaxIncrements.setPaintLabels(true);
        jSliderMaxIncrements.setPaintTicks(true);

        jButtonHelp.setText("Help");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });

        jLabelStrategyName1.setText("Strategy Name");

        jLabelIDValue.setText("0");

        jScrollPane1.setViewportView(jTextFieldStrategyNameValue);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonHelp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCompression, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEncryption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelStrategyName1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jLabelDestFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMaxIncrements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSliderMaxIncrements, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                            .addComponent(jScrollPaneDestFolder)
                            .addComponent(jCBCompression, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBEncryption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBStrategiesList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonDeleteStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonManageFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonChangeDestFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelIDValue, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAddTarget)
                                .addGap(11, 11, 11)
                                .addComponent(jButtonDeleteSelectedStrategy)))
                        .addContainerGap(243, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIDValue, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelStrategyName1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBStrategiesList, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDeleteStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEncryption, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBEncryption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCompression, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBCompression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonChangeDestFolder, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelDestFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneDestFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderMaxIncrements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaxIncrements, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonManageFilters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteSelectedStrategy)
                    .addComponent(jButtonAddTarget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManageFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageFiltersActionPerformed
        controller.manageFilters();
    }//GEN-LAST:event_jButtonManageFiltersActionPerformed

    private void jButtonDeleteSelectedStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSelectedStrategyActionPerformed
        if(jListTargets.getSelectedValue() != null){
            controller.removeTarget(jListTargets.getSelectedValue());
        }
    }//GEN-LAST:event_jButtonDeleteSelectedStrategyActionPerformed

    private void jButtonDeleteStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteStrategyActionPerformed
        controller.deleteStrategy();
    }//GEN-LAST:event_jButtonDeleteStrategyActionPerformed

    private void jCBStrategiesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBStrategiesListActionPerformed

        controller.updateView();
    }//GEN-LAST:event_jCBStrategiesListActionPerformed

    private void jButtonEditStrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditStrategyActionPerformed
        controller.editStrategy(jTextFieldStrategyNameValue.getText());
    }//GEN-LAST:event_jButtonEditStrategyActionPerformed

    private void jButtonAddTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTargetActionPerformed
        controller.addTarget();
    }//GEN-LAST:event_jButtonAddTargetActionPerformed

    private void jButtonChangeDestFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeDestFolderActionPerformed
        controller.pickDestinationFolder();
    }//GEN-LAST:event_jButtonChangeDestFolderActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        super.displayHelp();
    }//GEN-LAST:event_jButtonHelpActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTarget;
    private javax.swing.JButton jButtonChangeDestFolder;
    private javax.swing.JButton jButtonDeleteSelectedStrategy;
    private javax.swing.JButton jButtonDeleteStrategy;
    private javax.swing.JButton jButtonEditStrategy;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonManageFilters;
    private javax.swing.JComboBox<String> jCBCompression;
    private javax.swing.JComboBox<String> jCBEncryption;
    private javax.swing.JComboBox<String> jCBStrategiesList;
    private javax.swing.JLabel jLabelCompression;
    private javax.swing.JLabel jLabelDestFolder;
    private javax.swing.JLabel jLabelEncryption;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIDValue;
    private javax.swing.JLabel jLabelMaxIncrements;
    private javax.swing.JLabel jLabelStrategyName1;
    private javax.swing.JList<String> jListTargets;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneDestFolder;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSliderMaxIncrements;
    private javax.swing.JTextField jTextFieldDestFolder;
    private javax.swing.JTextField jTextFieldStrategyNameValue;
    // End of variables declaration//GEN-END:variables

    @Override
    public <ctrlT extends Controller> void setController(ctrlT c) {
        controller = c.toStrategyManagementController();
    }

    
    @Override
    public StrategyManagementDialog toStrategyManagementDialog() {
        return this;
    }

    
}
