package gui.settings;

import gui.Controller;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import gui.CenteredDialog;

/**
 * Dialog for changing settings
 * @author Fedrix
 */
public class SettingsDialog extends CenteredDialog {
    private final String title = "Settings";
    private final Dimension panelDimension = new Dimension(32767, 30);
    private SettingsController controller;
    protected final int DIALOG_WIDTH = 650;
    protected final int DIALOG_HEIGHT = 350;
    
    
    /**
     * Creates new form SettingsDialog
     * 
     * @param parent the JFrame parent of JDialog
     * @param modal set if the dialog is modal
     */
    public SettingsDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        this.setTitle(title);
        this.setMinimumSize(new Dimension(DIALOG_WIDTH, DIALOG_HEIGHT));
        this.setResizable(false);
        initComponents();
        initListeners();
        jButtonShutdown.setVisible(false);
    }
    
    public void setStrategyFolderPath(String path){
        jTextFieldPath.setText(path);
    }
    
    public void setStatus(boolean isError, String text){
        if(isError) jLabelStatus.setForeground(Color.RED);
        jLabelStatus.setText(text);
    }
    
    public void resetStatus(){
        jLabelStatus.setText("");
        jLabelStatus.setBackground(this.getBackground());
    }
    
    public void setThemeComboBoxModel(ComboBoxModel model){
        jComboBoxTheme.setModel(model);
    }
    public void setMainWindowWidthComboBoxModel(ComboBoxModel model){
        jComboBoxWidth.setModel(model);
    }
    public void setMainWindowHeightComboBoxModel(ComboBoxModel model){
        jComboBoxHeight.setModel(model);
    }
    
    public void showShutdownButton(boolean show){
        jButtonShutdown.setVisible(show);
    }
    

    
    private void initListeners(){
        jComboBoxTheme.addActionListener((ActionEvent e) -> { 
            controller.themeUpdatedAction();
        });
        jComboBoxWidth.addActionListener((ActionEvent e) -> { 
            controller.windowWidthUpdatedAction();
        });
        jComboBoxHeight.addActionListener((ActionEvent e) -> { 
            controller.windowHeightUpdatedAction();
        });
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelAppearance = new javax.swing.JPanel();
        jLabelWinSize = new javax.swing.JLabel();
        jComboBoxWidth = new javax.swing.JComboBox<>();
        jLabelWinSizeX = new javax.swing.JLabel();
        jComboBoxHeight = new javax.swing.JComboBox<>();
        jLabelTheme = new javax.swing.JLabel();
        jComboBoxTheme = new javax.swing.JComboBox<>();
        jPanelFolders = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextFieldPath = new javax.swing.JTextField();
        jLabelStrat = new javax.swing.JLabel();
        jButtonChgStratFolder = new javax.swing.JButton();
        jPanelStatus = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jPanelActions = new javax.swing.JPanel();
        jPanelLeftActions = new javax.swing.JPanel();
        jButtonShutdown = new javax.swing.JButton();
        jPanelRightActions = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonResetDefault = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane.setMinimumSize(new java.awt.Dimension(47, 121));

        jLabelWinSize.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelWinSize.setText("Main window starting size:");

        jLabelWinSizeX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWinSizeX.setText("x");

        jLabelTheme.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelTheme.setText("Theme:");

        javax.swing.GroupLayout jPanelAppearanceLayout = new javax.swing.GroupLayout(jPanelAppearance);
        jPanelAppearance.setLayout(jPanelAppearanceLayout);
        jPanelAppearanceLayout.setHorizontalGroup(
            jPanelAppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAppearanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAppearanceLayout.createSequentialGroup()
                        .addComponent(jLabelTheme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAppearanceLayout.createSequentialGroup()
                        .addComponent(jLabelWinSize, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelWinSizeX, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanelAppearanceLayout.setVerticalGroup(
            jPanelAppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAppearanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWinSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWinSizeX)
                    .addComponent(jComboBoxHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Appearance", jPanelAppearance);

        jTextFieldPath.setEditable(false);
        jTextFieldPath.setFont(new java.awt.Font("Liberation Sans", 2, 14)); // NOI18N
        jTextFieldPath.setText("Path");
        jScrollPane.setViewportView(jTextFieldPath);

        jLabelStrat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelStrat.setText("Strategies Folder:");

        jButtonChgStratFolder.setText("Change Folder");
        jButtonChgStratFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChgStratFolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFoldersLayout = new javax.swing.GroupLayout(jPanelFolders);
        jPanelFolders.setLayout(jPanelFoldersLayout);
        jPanelFoldersLayout.setHorizontalGroup(
            jPanelFoldersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFoldersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStrat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonChgStratFolder)
                .addContainerGap())
        );
        jPanelFoldersLayout.setVerticalGroup(
            jPanelFoldersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFoldersLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelFoldersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelStrat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonChgStratFolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Folders", jPanelFolders);

        jPanelStatus.setMaximumSize(new java.awt.Dimension(32767, 10));
        jPanelStatus.setMinimumSize(new java.awt.Dimension(86, 17));

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanelStatus.add(jLabelStatus);

        jPanelActions.setMaximumSize(new java.awt.Dimension(32767, 10));
        jPanelActions.setMinimumSize(new java.awt.Dimension(86, 17));
        jPanelActions.setLayout(new javax.swing.BoxLayout(jPanelActions, javax.swing.BoxLayout.LINE_AXIS));

        jPanelLeftActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonShutdown.setText("Shutdown");
        jButtonShutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShutdownActionPerformed(evt);
            }
        });
        jPanelLeftActions.add(jButtonShutdown);

        jPanelActions.add(jPanelLeftActions);

        jPanelRightActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanelRightActions.add(jButtonSave);

        jButtonCancel.setText("Close");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelRightActions.add(jButtonCancel);

        jButtonResetDefault.setText("Reset to defaults");
        jButtonResetDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetDefaultActionPerformed(evt);
            }
        });
        jPanelRightActions.add(jButtonResetDefault);

        jPanelActions.add(jPanelRightActions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanelActions, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        controller.saveAction();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonResetDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetDefaultActionPerformed
        controller.resetAction();
    }//GEN-LAST:event_jButtonResetDefaultActionPerformed

    private void jButtonChgStratFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChgStratFolderActionPerformed
        controller.strategyFolderAction();
    }//GEN-LAST:event_jButtonChgStratFolderActionPerformed

    private void jButtonShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShutdownActionPerformed
        controller.shutdownAction();
    }//GEN-LAST:event_jButtonShutdownActionPerformed
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonChgStratFolder;
    private javax.swing.JButton jButtonResetDefault;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonShutdown;
    private javax.swing.JComboBox<String> jComboBoxHeight;
    private javax.swing.JComboBox<String> jComboBoxTheme;
    private javax.swing.JComboBox<String> jComboBoxWidth;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStrat;
    private javax.swing.JLabel jLabelTheme;
    private javax.swing.JLabel jLabelWinSize;
    private javax.swing.JLabel jLabelWinSizeX;
    private javax.swing.JPanel jPanelActions;
    private javax.swing.JPanel jPanelAppearance;
    private javax.swing.JPanel jPanelFolders;
    private javax.swing.JPanel jPanelLeftActions;
    private javax.swing.JPanel jPanelRightActions;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables

    @Override
    public <ctrlT extends Controller> void setController(ctrlT c) {
        assert(c instanceof SettingsController);
        controller = c.toSettingsController();
    }

    @Override
    public SettingsDialog toSettingsDialog() {
        return this;
    }
    
    
}
